# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a6d4b1678da9f7c7471d11120535349deffaef85c0b9370dd3e4437f93c722dff53b096651cb85c7fd64d66c7af25a84080da2387afd47933efce1fd02a4a82

test:
  secret_key_base: 9b1dfd984bfefe3e48056e94647815f5fa5c89950265da85fe00ca37a50b61a5010552bc0d95b6fa3f8cc5053695632f6c1f5dc84b6e9215b604b9908f1b7300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
